version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/web/web" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget" # See documentation for possible values
    directories:
      - "/*"
      - "/web/*"
    schedule:
      interval: "weekly"
