version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "NuGet" # See documentation for possible values
    directories:
      - "/*"
      - "/web/*"
      - "/web.Client/*"
    schedule:
      interval: "weekly"
